# Generated by Django 3.2.6 on 2021-11-13 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=128, verbose_name='Name')),
                ('middle_name', models.CharField(max_length=128, verbose_name='Middle name')),
                ('surname', models.CharField(max_length=128, verbose_name='Surname')),
                ('date_birthday', models.DateField(verbose_name='Birthday')),
                ('sex', models.CharField(choices=[('male', 'Мужской'), ('female', 'Женский')], max_length=6, verbose_name='Sex')),
                ('passport_series', models.CharField(max_length=4, verbose_name='Passport series')),
                ('passport_number', models.CharField(max_length=6, verbose_name='Passport number')),
                ('residence_address', models.CharField(default='Томская обл, г Томск, ул Источная, д. 42, кв.2', max_length=256, verbose_name='Address')),
                ('snills', models.CharField(default='', max_length=11, null=True, verbose_name='Snils')),
                ('oms', models.CharField(default='', max_length=11, null=True, verbose_name='OMS')),
                ('medical_organization', models.CharField(default='ОГАУЗ "Поликлиника №4"', max_length=128, verbose_name='Medical organization')),
            ],
        ),
    ]
