# Generated by Django 3.2.6 on 2021-11-13 10:15

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_userdata_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='vaccine_id',
            field=models.CharField(default=core.models.generate_vaccine_id, max_length=16, verbose_name='Vaccine id'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
